### ISSUE TITLE
Micronaut-jdbc doesn't cascade one-to-many for Embeddable entities

### ISSUE THREAD

**Issue by lucas-scampos** [micronaut-projects/micronaut-data#1173]
Greetings,

I have a standard one-to-many relationship between Template and Tags, where Template can have many tags.

However, the Tag entity has a composite id defined by @EmbeddedId. I'm suspecting that because of this, micronaut-jdbc is not able to cascade the save to the tag entity. From the console, I'm able to see that it generates the correct SQL insert, but it doesn't bind any values to the INSERT and this results in the child (Tag) not being persisted.

### Steps to Reproduce

1. Start micronaut app
2. curl --request GET \
  --url http://localhost:8080/1
3. Verify that template_tag is not persisted

### Expected Behaviour

When we save the Template entity, the Tag entity should also be saved (because of the cascading)

### Actual Behaviour

 micronaut-data generates the INSERT statements
`Executing Batch SQL Insert: INSERT INTO `template_tag` (`tag`,`template_id`) VALUES (?,?)`
but it doesn't bind the values nor persists the template_tag entity

### Environment Information

- **Operating System**: MacOS Cataline 10.15.7
- **Micronaut Version:** 3.0.1
- **JDK Version:** 11

### Example Application

https://github.com/lucas-scampos/cascade-embbeded-jdbc

**Comment by Chris-V** [comment]
We are facing this issue as well and this forces us to manage our cascade operations manually.

I tried to come up with a fix but I have yet to find out how everything is tied together here.

**Comment by Chris-V** [comment]
I digged a little bit more and here's what I have so far.

Cascaded entities are vetoed to true here https://github.com/micronaut-projects/micronaut-data/blob/master/data-jdbc/src/main/java/io/micronaut/data/jdbc/operations/DefaultJdbcRepositoryOperations.java#L286

I then tried to set vetoed=false to see what happens, but the generated SQL was invalid (quotes are `"` instead of backticks). So I noticed that the dialect is set to ANSI even though `@JdbcRepository(dialect = Dialect.MYSQL)` is set on the repository. 

I traced it back to https://github.com/micronaut-projects/micronaut-data/blob/master/data-jdbc/src/main/java/io/micronaut/data/jdbc/operations/DefaultJdbcRepositoryOperations.java#L746 where `queryBuilders` is empty and `DEFAULT_SQL_BUILDER` is returned with the ANSI dialect.

This may be the same or a different issue. I don't know micronaut-data well enough to tell. Hopefully this summary can help someone else find the root cause

**Comment by dstepanov** [comment]
It looks like we do not persist entities that have set id, which is not correct for embedded ids. I will allow it but I think there might be cases when we shouldn't persist the child with embedded id and no generated values.

**Comment by dstepanov** [comment]
@Chris-V Please create a separate issue and a reproducer. There is no way `queryBuilders` can be empty as it should put all of the existing repositories there, so it's very strange. You can try to add a test to the project directly as I did in the attached PR.

**Comment by soberich** [comment]
@dstepanov bug is still present, I'll come up with repro

**Comment by Chris-V** [comment]
@soberich our issue was caused by the datasource not being named "default". I opted to change our code instead and didn't create a repro by lack of time. Hopefully this helps you with doing a repro project though.
