### ISSUE TITLE
Find by foreign key does not compile when there are 2 similarly named variables referencing the other tables in the POJO

### ISSUE THREAD

**Issue by athkalia** [micronaut-projects/micronaut-data#1200]
### Expected Behavior

A bit of a weird one.

The repository definition:

```
@JdbcRepository(dialect = Dialect.MYSQL)
interface RepoScanAnalysisResultsRepository : CrudRepository<RepositoryScanAnalysisResultDbModel, String> {
    override fun findAll(): List<RepositoryScanAnalysisResultDbModel>

    fun findByRepositoryScanId(repositoryScanId: String): List<RepositoryScanAnalysisResultDbModel>
}
```

It doesn't work with this `RepositoryScanAnalysisResultDbModel`:
```
@Table(name = "REPOSITORY_SCAN_ANALYSIS_RESULTS")
data class RepositoryScanAnalysisResultDbModel(
    @field:Id @field:GeneratedValue var id: String? = null,
    @ManyToOne val repositoryScan: RepositoryScanDbModel? = null,
    @ManyToOne val repository: RepositoryDbModel? = null,
 )
```

But it works with this one:

```
@Table(name = "REPOSITORY_SCAN_ANALYSIS_RESULTS")
data class RepositoryScanAnalysisResultDbModel(
    @field:Id @field:GeneratedValue var id: String? = null,
    @ManyToOne val repositoryScan: RepositoryScanDbModel? = null,
  //  @ManyToOne val repository: RepositoryDbModel? = null,
 )
```

The only difference is the commented-out line. It seems like because `repositoryScan` and `repository` both start with `repository` the annotation processor gets confused.

### Version

2.5.13

**Comment by radovanradic** [comment]
This should work since fix for #2474 should resolve this issue as well.
Then repository method would look like this:
`fun findByRepositoryScan_Id(repositoryScanId: String): List<RepositoryScanAnalysisResultDbModel>`
like suggested [here](https://jakarta.ee/specifications/data/1.0/data-1.0.0-b3#_entity_property_names) to use underscore to avoid ambiguity between property names/paths.
The fix will be available in Micronaut Data 4.1.3 and later. Please reopen if you are still seeing issues after this fix in Micronaut 4.
