### ISSUE TITLE
Transaction failures with multiple data sources

### ISSUE THREAD

**Issue by pjverity** [micronaut-projects/micronaut-data#142]
I have defined two identical datasources and two JPA configurations. While using the `default` datasource works as expected, setting the `@Repository` annotation to use a secondary datasource results in the following error:

    Caused by: org.hibernate.PersistentObjectException: detached entity passed to persist: co.uk.vhome.micronaut.TestEntity

I have an example that reproduces the issue here:

https://github.com/pjverity/mn-data-multiple-ds.git

Switch the commented annotations in [TestRepository.java](https://github.com/pjverity/mn-data-multiple-ds/blob/1b56d249fdeecd06e0c4ec9e407b0b4748d02f1e/src/main/java/co/uk/vhome/micronaut/TestRepository.java#L6) to see it work/break.

An example HTTP request would be:

    PUT http://localhost:8080/1
    Content-Type: application/json
    {
      "value": "Bye"
    }

The result is the same for both H2 and Postgres databases. The example uses Flyway to populate an H2 database for the test

**Comment by graemerocher** [comment]
This is not actually a bug. The behavior can be explained as follows:

1. The controller defines a `@Transactional` annotation that uses the default data source (no value is passed to the annotation) https://github.com/pjverity/mn-data-multiple-ds/blob/master/src/main/java/co/uk/vhome/micronaut/TestController.java#L46
2. When the `TestRepository` uses the default data source this causes the behaviour to pass because the outer transaction started by the controller allows sharing the same session between the calls to `findById` and `save` presented in the example
3. When the `TestRepository` is changed to use a different data source then the session is no longer shared, hence the object is read in one transaction and passed to `save` in a detached state to another transaction resulting in the error.

To make the example work with the second data source you also need to change the `@Transactional` definition in the controller.

**Comment by pjverity** [comment]
Many thanks for highlighting that. If anyone else falls in to this (likely common) scenario too, the resolution is to name the transaction manager used to manage the transactions of the _other_ datasource, in my case I had a second datasource called `other` in my `application.yml`, so the annotation simply becomes `@Transactional("other")`
