### ISSUE TITLE
existsBy for Kotlin r2dbc reactive fails on non-existing record

### ISSUE THREAD

**Issue by ondrej-hrstka** [micronaut-projects/micronaut-data#1639]
This bug occures from Micronaut Version 3.5.x. For 3.4.x (and older) this works as expected.

### Expected Behavior

I have a `ReactiveCrudRepository` with method `existsByFoo(...): Mono<Boolean>`. When I call this method for **non-existing** record, I should get `false` returned. For existing record this works as excepted (returns `true`).

### Actual Behaviour

The returned value is `null`. This is even bigger problem for coroutines, where runtime fails on conversion from `null` to non-nullable `Boolean`.

**Workaround:** Use `Mono<Boolean?>` for reactive and `Boolean?` for coroutines approach.

### Steps To Reproduce

In sample application run `./gradlew test`. 

### Environment Information

- OS: macOS 12.4
- JDK: 17

### Example Application

https://github.com/ondrej-hrstka/micronaut-existsby-r2dbc-kotlin-error-bug

### Version

3.5.x

**Comment by ondrej-hrstka** [comment]
@dstepanov It's the same. At least I hope, I've set the version for all (2) dependencies: https://github.com/ondrej-hrstka/micronaut-existsby-r2dbc-kotlin-error-bug/commit/b2146a68bd0306ec1dbbb0a385800d13fdaeb9b3

**Comment by jmsantorum** [comment]
same here! but in our case, we can go further:

What we faced is that since micronaut-data version 3.4.2 (included) the `existsByXXX` methods don't work as expected, I mean:

- when there are no elements that match it should return `false` but it returns `null`
- when there is only one match element it returns `true` as expected
- when there is more than one matching element it should return `true` but in this case, it throws a `NonUniqueResultException` exception

Analyzing deeper into the possible root cause I saw that on previous versions (`< 3.4.2`) the `exists` method implementation had the following, making the method return the expected results
```
.collectList().map(results -> !results.isEmpty()).defaultIfEmpty(false);
```

3.4.1: https://github.com/micronaut-projects/micronaut-data/blob/68ba793c1cf2244a7aab21e45a317eb1e8fc5bf1/data-r2dbc/src/main/java/io/micronaut/data/r2dbc/operations/DefaultR2dbcRepositoryOperations.java#L499

but after [a refactor](https://github.com/micronaut-projects/micronaut-data/pull/1556) on version 3.4.2 now the method differs delegating on making it not work as expected
```
return executeAndMapEachRowSingle(statement, row -> true);
```

3.4.2: https://github.com/micronaut-projects/micronaut-data/blob/db6d65633c18ce3b6be9d370a79cc4f2d09e0ff7/data-r2dbc/src/main/java/io/micronaut/data/r2dbc/operations/DefaultR2dbcRepositoryOperations.java#L551

I would like to help with it, but not sure about the best approach to fix it
