### ISSUE TITLE
UpdateAll does not update all many-to-many associations with the same object

### ISSUE THREAD

**Issue by christopher-mohr** [micronaut-projects/micronaut-data#1644]
### Expected Behavior

Individual calls of `update` should lead to the same result as one call of `updateAll` on a list with items with respect to many-to-many associations to the same object.

### Actual Behaviour

Only the many-to-many association of the first item in the list seems to be updated/created.

There is an `INSERT` statement but no values are bound.

```
[main] DEBUG io.micronaut.data.query - Executing SQL query: INSERT INTO "student_course" ("student_id","course_id") VALUES (?,?)
```

### Steps To Reproduce

1. Clone repository
2. Run `mvn -Dtest='com.example.DemoSpec' test`

### Environment Information

- Operating System: macOS `11.6.5`
- JDK Version: `11`

### Example Application

https://github.com/christopher-mohr/reproduce-update-all-bug

### Version

3.5.3

**Comment by dstepanov** [comment]
Thanks for the report! Looking at it, I think the single update shouldn't work in the first place.Because we don't have any kind of session, there is no way to tell which many-to-many relations were already persisted or removed from the entity. The only allowed use-case is when the many-to-many relation entity is new (no id), so we can assume it's being added.

Essentially there are two types of cascades happening:
- update the values of the related entity
- update the many-to-many relation which manifests in insert/remove of the join table entries.

We can probably do variations of `INSERT ON CONFLICT DO NOTHING` to add missing entries or 'remove all and insert all' IMHO none of them are good solutions.

I would recommend you handle many-to-many relations manually.

**Comment by christopher-mohr** [comment]
Thanks for the feedback!

**Comment by dstepanov** [comment]
Closing it as not planned
