### ISSUE TITLE
Multi tenancy support

### ISSUE THREAD

**Issue by RuiffCardoso** [micronaut-projects/micronaut-data#253]
Hi, from the last couple of days I've been trying to implement multitenancy on while using micronaut-data but failed. I tried creating custom HibernateTransactionManager's and a few other things but it didn't work. Tried to look at Spring Boot implementation in order to copy the behaviour, but it seams they always created a new EntityManagerFactory when a request arrives (on OpenEntityManagerInViewInterceptor) so the current tenantIdentifier is always obtained. In micronaut I couldn't make this behaviour so the tenantIdentifier is just created a single time when the SessionFactoryBuilder is created and then it never updates. 
Where should I be looking if I wanted to implement multitenant on micronaut-data? I've read that it is on the roadmap the support for the multitenancy, what is the priority on this? Is it something to be released on the 1.0 or more down the line? Thanks

**Comment by graemerocher** [comment]
Definitely planned. Not sure it will make 1.0. Maybe 1.1 at this stage. So that would be early next year time frame.

**Comment by Panthaaaa** [comment]
Do you have any update regarding this topic? (Or maybe link a public roadmap)
We are currently building a new app with Micronaut + Kotlin and need multi-tenancy, therefore it would be nice to know how you plan to build this.

**Comment by graemerocher** [comment]
No update, still planned to work on this soon, but haven't got to it yet. The idea would be to allow switching tenant using an argument for dynamic tenants or alternatively injecting different repository instances for static resolution.

**Comment by tcardoso** [comment]
@Panthaaaa I was able to reach a partial solution that solves my scenario. 
I noticed that @Repository can receive the name of the datasource and I've started working from there.

changed code:

Assume that the tenantIdentifier corresponds to your datasource qualifier name (written on properties).

**io.micronaut.context.BeanDefinitionDelegate:** 
`public T build(BeanResolutionContext resolutionContext, BeanContext context, BeanDefinition<T> definition) throws BeanInstantiationException `
 `...`
`if (this.definition instanceof ParametrizedBeanFactory)`
`....`
//using the tenantIdentifier as if it was the repository qualifier
`for (Argument argument : requiredArguments) {`
`                        Class argumentType = argument.getType();`
`                        if (argumentType == DataSource.class)`
`                             named = tenantIdentifier `

**io.micronaut.data.intercept.DataIntroductionAdvice:** 
`public Object intercept(MethodInvocationContext<Object, Object> context) {`
`RepositoryMethodKey key = new RepositoryMethodKey(context.getTarget(), context.getExecutableMethod(), tenantIdentifier); \\ add the tenantIdentifier and change the io.micronaut.data.intercept.RepositoryMethodKey to have in consideration each datasource`
`replace String dataSourceName = context.stringValue(Repository.class).orElse(null); by the tenantIdentifier`

**io.micronaut.data.intercept.RepositoryMethodKey:** 
// added tenantIdentifier
`public RepositoryMethodKey(Object repository, ExecutableMethod method, String tenantIdentifier) {` 
`this.hashCode = Objects.hash(repository, method, tenantIdentifier); `
`..`
`public boolean equals(Object o)`
`..`
`return repository.equals(that.repository) &&  method.equals(that.method) && tenantId.equals(that.tenantIdentifier); `

//Overriding this class will allow micronaut-data transactions to handle multitenant
**io.micronaut.transaction.interceptor.TransactionalInterceptor**
//Add a new level to the mapper to consider the tenantIdentifier as key
`Replace: private final Map<ExecutableMethod, TransactionInvocation> transactionInvocationMap = new ConcurrentHashMap<>(30); `
`With: private final Map<String,Map<ExecutableMethod, TransactionInvocation>> tenantTransactionInvocationMap = new ConcurrentHashMap<>();`
`...`
//Resolve the mapper according to the tenantIdentifier
`public Object intercept(MethodInvocationContext<Object, Object> context) { `
`final TransactionInvocation transactionInvocation = tenantTransactionInvocationMap.get(tenantIdentifier)
                .computeIfAbsent(context.getExecutableMethod(), executableMethod -> {`
`...`
`tenantTransactionInvocationMap.computeIfAbsent(tenantIdentifier, ret -> new ConcurrentHashMap<ExecutableMethod, TransactionInvocation>(30)); //to create a new map if the tenant is new`
`..`
`Replace: final String qualifier = executableMethod.stringValue(TransactionalAdvice.class).orElse(null);  `
`with:  String qualifier = "tenantIdentifier";`


Pitfalls:
- I am overriding the @Repository(datasourceQualifier) and @Transaction(datasourceQualifier) functionality since I don't use them, but you can re-write the code to make use of them.
- I am sure that I have only covered 5% of the multitenant issue, but in my scenario this was enough (so far)


You can pass the tenantIdentifier through a bean since you always have the Application context, since its a Singleton you can just inject it. I have coded my TentantResolver with a @RequestScope since my tenantIdentifier is sent through the Request Header.

You can even insert new datasources dynamically by using the `PropertySource` and passing it to the application context ( `applicationContext.getEnvironment().addPropertySource(propertySource);`  )

If during the code execution you see any Bean not Found for qualifier named 'default', is because somewhere in the micronaut code we need to take in consideration the tenantId

**Comment by Panthaaaa** [comment]
Thank you for the helpful steps! It helps me with wiring, but what still isn't clear to me: How do you save the data in the database: tenant column vs. tenant schema vs tenant database. 
Is a new datasource a new database in your case or am I missing something?

**Comment by tcardoso** [comment]
Micronaut already supports multitenancy by column when using the same schema.
I needed to have multitenancy separated by database or schema, so I have multiple datasources defined in my properties:
`datasources:`
`  default:`
`    url: jdbc:mysql://localhost:3306/data1`
`    username:  $$$$$$$$$`
`    password: $$$$$$$$$$$`
`    driverClassName: com.mysql.cj.jdbc.Driver`
`    autoCommit: false`
`  abc: `
`    url: jdbc:mysql://192.168.1.35:3306/data1`
`    username:  $$$$$$$$$`
`    password: $$$$$$$$`
`    autoCommit: false`

and I use those datasource qualifiers (in this scenario, abc or default (none)) to indicate where the data should be saved

**Comment by tqad** [comment]
Hi, I've a Demo Project with fewer steps to enable multi-tenancy in Micronaut. As far as I've tested all features of micronaut-data seems to work. 

[Sample Project](https://github.com/tqad/micronaut-data-jpa-multi-tenant)

**Comment by paulbandler** [comment]
> Micronaut already supports multitenancy by column when using the same schema.
> I needed to have multitenancy separated by database or schema, so I have multiple datasources defined in my properties:
> `datasources:`
> ` default:`
> ` url: jdbc:mysql://localhost:3306/data1`
> ` username: $$$$$$$$$`
> ` password: $$$$$$$$$$$`
> ` driverClassName: com.mysql.cj.jdbc.Driver`
> ` autoCommit: false`
> ` abc:`
> ` url: jdbc:mysql://192.168.1.35:3306/data1`
> ` username: $$$$$$$$$`
> ` password: $$$$$$$$`
> ` autoCommit: false`
> 
> and I use those datasource qualifiers (in this scenario, abc or default (none)) to indicate where the data should be saved

@tqad Did you achieve your MT solution based on Micronaut Data-JDBC, or JPA/Hibernate?  I have been investigating whether MT support for MN-Data-JDBC and yours is sounds like it could be that...?

**Comment by paulbandler** [comment]
> Micronaut already supports multitenancy by column when using the same schema.
> I needed to have multitenancy separated by database or schema, so I have multiple datasources defined in my properties:
> `datasources:`
> ` default:`
> ` url: jdbc:mysql://localhost:3306/data1`
> ` username: $$$$$$$$$`
> ` password: $$$$$$$$$$$`
> ` driverClassName: com.mysql.cj.jdbc.Driver`
> ` autoCommit: false`
> ` abc:`
> ` url: jdbc:mysql://192.168.1.35:3306/data1`
> ` username: $$$$$$$$$`
> ` password: $$$$$$$$`
> ` autoCommit: false`
> 
> and I use those datasource qualifiers (in this scenario, abc or default (none)) to indicate where the data should be saved

@tcardoso  Did you achieve your MT solution based on Micronaut Data-JDBC, or JPA/Hibernate? I have been investigating whether MT support for MN-Data-JDBC and yours is sounds like it could be that...?

**Comment by destan** [comment]
> //Overriding this class will allow micronaut-data transactions to handle multitenant
> **io.micronaut.transaction.interceptor.TransactionalInterceptor**

@tcardoso you suggested _overriding_ `TransactionalInterceptor` but how it's possible? 

I've tried with `@Replaces` annotation 

```kotlin
@Prototype
@Replaces(TransactionalConnectionInterceptor::class)
open class CustomInterceptor : MethodInterceptor<Connection, Any> {
...
...
```

but it required a `@Introduction` annotation. The exception is


> io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type [io.micronaut.transaction.jdbc.TransactionalConnection$Intercepted]: At least one @Introduction method interceptor required, but missing. Check if your @Introduction stereotype annotation is marked with @Retention(RUNTIME) and @Type(..) with the interceptor type. Otherwise do not load @Introduction beans if their interceptor definitions are missing!


Moreover, adding an `@Introduction` annotation on the replacing MethodInterceptor implementation didn't change the error.

**Comment by tcardoso** [comment]
Hi @destan

The only way I found to "replace" the transactionInterceptor, was to add on my project a copy of the TransactionInterceptor.class with my changes, in the same package name (io.micronaut.transaction.interceptor)

This way the Class Loader will load my class instead of the micronaut one. It's dirty but it works! :(

Everytime I update the version on micronaut, I have to be carefull and check if the class has any change.

**Comment by tcardoso** [comment]
Hi @paulbandler. 

I've missed your comment. I was able to get it working with both hibernate and micronaut-data, or at least, it seems to work on my scenarios.

My biggest challenge was not related with obtaining the correct bean, but getting the Transactions to work (commits, rollbacks, etc) with the correct database during the iteration.

I thought about making a PR for the micronaut project. Maybe adding an annotation to a Repository class to trigger the Datasource to be selected based on a qualifier that could be obtained in runtime. But I didn't know how to test my solution or even if it would be usefull.

**Comment by destan** [comment]
@tcardoso why didn't you prefer Hibernate's `AbstractDataSourceBasedMultiTenantConnectionProviderImpl` which makes selecting a datasource according to a `tenantId` easy but instead go for overriding `@Repository("datasourceName")`?

Did you try and fail? Was there any catch?

**Comment by tqad** [comment]
Hi, I have created a running example of Hibernate - Multi tenancy on database level based on Micronaut 3.6.1.
I hope the example helps someone. 

@destan I used Hibernate's implementation as far as possible but in my case I need to determine the tenant by Micronauts Tenant Resolver. 

[Sample Project](https://github.com/tqad/micronaut-data-jpa-multi-tenant)

**Comment by akshayvadher** [comment]
> Hi, I have created a running example of Hibernate - Multi tenancy on database level based on Micronaut 3.6.1. I hope the example helps someone.
> 
> @destan I used Hibernate's implementation as far as possible but in my case I need to determine the tenant by Micronauts Tenant Resolver.
> 
> [Sample Project](https://github.com/tqad/micronaut-data-jpa-multi-tenant)

This works like a charm. Thanks a lot. I will add a link your project to all the places I asked for sample of this problem.

**Comment by destan** [comment]
@tqad 's sample projects works indeed. I'd like to share our solution which is a slightly modified version of the sample project's `AbstractDataSourceBasedMultiTenantConnectionProviderImpl` implementation.

Our version supports dynamic tenants by using only one datasource and setting unqiue database `scheme` on the db connection for every tenant.

```kotlin
class MultiTenantConnectionProviderImpl : AbstractDataSourceBasedMultiTenantConnectionProviderImpl() {

    private val log = LoggerFactory.getLogger(javaClass)

    override fun selectAnyDataSource(): DataSource {

        val dataSource = ApplicationContextProvider.applicationContext().getBean(DataSource::class.java)
        if (dataSource is DelegatingDataSource) {
            return dataSource.targetDataSource
        }
        throw IllegalStateException("Data source should have been of type DelegatingDataSource but it's ${dataSource.javaClass}")
    }

    override fun selectDataSource(tenantIdentifier: String?): DataSource {
        // As we're using scheme-per-tenant we can use the same datasource for all tenants.
        // We just need to set the current tenant's scheme for any connection
        return selectAnyDataSource()
    }

    override fun getConnection(tenantIdentifier: String?): Connection {
        val connection = super.getConnection(tenantIdentifier)
        connection.schema = tenantIdentifier

        if (log.isDebugEnabled) {
            log.debug("getConnection: Schema tenantIdentifier '$tenantIdentifier' is set.")
        }
        return connection
    }

    override fun getAnyConnection(): Connection {
        val connection = super.getAnyConnection()
        connection.schema = DEFAULT_SCHEMA_ID_STR

        if (log.isDebugEnabled) {
            log.debug("getConnection: Schema tenantIdentifier '$DEFAULT_SCHEMA_ID_STR' is set.")
        }

        return connection
    }

    override fun releaseAnyConnection(connection: Connection?) {
        connection?.schema = null

        if (log.isDebugEnabled) {
            log.debug("releaseAnyConnection: Schema reset.")
        }

        super.releaseAnyConnection(connection)
    }

    override fun releaseConnection(tenantIdentifier: String?, connection: Connection?) {
        connection?.schema = null

        if (log.isDebugEnabled) {
            log.debug("releaseConnection: Schema reset.")
        }

        super.releaseConnection(tenantIdentifier, connection)
    }

}
```

**Comment by richmidwinter** [comment]
Any sign of this arriving in the project proper?

**Comment by dstepanov** [comment]
Makes senses

**Comment by Saumya999** [comment]
If you see in the Doc - they are maintaining 2 server urls in the application.yml for FOO and Bar. 
Here my requirement is little different. But in my case beforehand I don't know how many tenants will be there. 

For example: 
one endpoint = **/register** that will be public which doesn't need any tenantId in Header . It will create and registration id for the customer. Basically That generated Id will be tenant-id for respective calls. and tenant-Id will be the databse Name. Database will contain - per customer products, orders, billings etc as collections. (B2B) 

application.yml

```
mongodb:
  uri: 'mongodb://localhost:27017/{tenantId}
```

This is something I need. - For now I am mentioning one fixed value in place of tenantId variable. 
  
  this tenantId I am getting below 
  
  ```
@Singleton
@Filter("/**")
class TenantFilter(private val connectionStorage: ConnectionStorage) : HttpServerFilter{

    // TODO Multi-Tenancy implementation to add x-tenant-id in Header for dynamic database

    override fun doFilter(request: HttpRequest<*>?, chain: ServerFilterChain?): Publisher<MutableHttpResponse<*>> {
        val attribute: @Nullable String = request?.headers?.get("x-tenant-id") ?: throw RuntimeException("Missing Tenant Header")
        if (chain != null) {
            connectionStorage.setConnection(attribute)
            return chain.proceed(request)
        } else {
            throw RuntimeException("proper request chaining not happening")
        }
    }


}
```

```
@Singleton
class ConnectionStorage {
    private var threadLocal:ThreadLocal<String> = ThreadLocal()
    fun setConnection(tenantId: String) {
        threadLocal.set(tenantId)
    }
    fun removeConnection(tenantId: String) {
        threadLocal.remove()
    }
    fun getConnection(): String {
        return threadLocal.get()
    }
}
```
  
  
  Now tenantId is set in ThreadLocal storage. I need to dynamically override the connection String of MongoDB in runtime.

**Comment by dstepanov** [comment]
@Saumya999 please keep the discussion in one place
