### ISSUE TITLE
How to print JdbcRepository queries with params using props?

### ISSUE THREAD

**Issue by ArthurHarkivsky** [micronaut-projects/micronaut-data#2597]
### Issue description

Hello! Please, how to print JdbcRepository queries with params using props?

**Comment by radovanradic** [comment]
What do you mean print queries, do you mean log?
If you mean logging, you can do this: https://sergiodelamo.com/blog/micronaut-data-log-query.html (debug level is enough).

Also, instead of opening issues for question you can use [Discussions](https://github.com/micronaut-projects/micronaut-data/discussions) or join [Micronaut Discord channel](https://discord.com/channels/1121511613250412714/1122324729756385300).

**Comment by ArthurHarkivsky** [comment]
THANK YOU!
