### ISSUE TITLE
Repository$Intercepted$$proxy instances are not GC'd 

### ISSUE THREAD

**Issue by crbudzeak** [micronaut-projects/micronaut-data#283]
### Steps to Reproduce

1. ./gradlew run
2. Attach jvisualvm to running process
3. Click on Sampler tab and start memory sample
4. Filter for proxyissue
5. Let time pass and a GC or two happen, notice the repository proxies continue to increase with each `@Scheduled` execution of `Runner.java$run()`

### Expected Behaviour

Repository proxy instances to be GC'd with other class instances.

### Actual Behaviour

Repository proxy instances increase until OOME.

### Environment Information

- **Operating System**: OSX and Linux
- **Micronaut Version:** 1.2.6 and 1.3.0.M1
- **Micronaut Data Version:** 1.0.0.M5
- **JDK Version:** 1.8.0_131 and 1.8.0_232

### Example Application

- https://github.com/crbudzeak/micronaut-data-proxy-issue

<img width="910" alt="Screen Shot 2019-11-23 at 1 26 25 PM" src="https://user-images.githubusercontent.com/7129730/69484000-02e98700-0dfc-11ea-97cc-3a65a853dfb0.png">

**Comment by graemerocher** [comment]
Wow good catch. Turns out the framework makes all sorts of assumptions about repositories being singletons and in fact there is no scope specified by default on repositories so they end up being prototype which should not be the case. This has been fixed, however you can workaround the issue by adding `@Singleton` to your repository definitions.

**Comment by crbudzeak** [comment]
Fantastic. I'm loving micronaut. Keep up the good work!

**Comment by graemerocher** [comment]
Great! Thanks for the feedback
