### ISSUE TITLE
Broken images in docs

### ISSUE THREAD

**Issue by sdelamo** [micronaut-projects/micronaut-data#2914]
@graemerocher 
> did something break with images and doc publishing? The image at https://micronaut-projects.github.io/micronaut-data/4.7.0/guide/#querying is broken

That file is gone from 4.7.x finderpattern.svg 

@wetted please investigate when that file got removed. 

it is in gh-pages branch

**Comment by wetted** [comment]
ping @sdelamo @graemerocher 

This image hasn't been in any gh-pages branch `/x.y.z` publication since 1.0.x variants (1.0.0.M1, 1.0.0.M2, 1.0.0.M3, 1.0.0.TEST, 1.0.x).

Note, that it is in `/latest` and `/snapshot` which is why we were used to seeing it online, until we changed docs pages to stop using `latest` by default.

<img width="914" alt="Screenshot 2024-04-26 at 11 44 50 AM" src="https://github.com/micronaut-projects/micronaut-data/assets/8419491/94fdbba4-1630-44a5-baff-b41138a6853b">

**Comment by sdelamo** [comment]
> ping @sdelamo @graemerocher
> 
> This image hasn't been in any gh-pages branch `/x.y.z` publication since 1.0.x variants (1.0.0.M1, 1.0.0.M2, 1.0.0.M3, 1.0.0.TEST, 1.0.x).
> 
> Note, that it is in `/latest` and `/snapshot` which is why we were used to seeing it online, until we changed docs pages to stop using `latest` by default.
> 

Please, fix it so that it shows. Add it back to the docs.

**Comment by wetted** [comment]
> Please, fix it so that it shows. Add it back to the docs.

OK, I'll check all images (if there are more). I'll work on this next week.
