### ISSUE TITLE
JDBC: Save entity inserts a new row when updating an entity 

### ISSUE THREAD

**Issue by Uniqen** [micronaut-projects/micronaut-data#41]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce
1. Using JDBC and a CrudRepocitory
1. Create and save entity
1. Update and save entity again

### Expected Behaviour
Expected behaviour is that the existing table row is updated. 

According to the documentation:
> To update an entity you can once again pass the entity to the the save method:

### Actual Behaviour
A new row is inserted. The saved entity is updated with the new id.

### Environment Information

- **Operating System**: OSX
- **Micronaut Version:** 1.2.0-RC2
- **Predator Version:** 1.0.0.BUILD-SNAPSHOT from July 23 2019.
- **JDK Version:** Oracle JDK 1.8.0_191

### Example Application

I've added test case that reproduces the issue in the _example-jdbc_-project in fork [https://github.com/Uniqen/micronaut-predator](https://github.com/Uniqen/micronaut-predator)

See [examples/example-jdbc/src/test/java/example/repositories/OwnerRepositoryTest.java](https://github.com/Uniqen/micronaut-predator/blob/master/examples/example-jdbc/src/test/java/example/repositories/OwnerRepositoryTest.java)

**Comment by graemerocher** [comment]
This is actually by design although should be better documented. The JDBC implementation doesn't include any dirty checking or persistence session notion. So you have to define explicit `update` methods for updates. For example:

```java
void updateName(@Id Long id, String name)
```

The alternative would be to check if an ID is already present and then do an update, however that doesn't work in the case where manually assigned IDs are used.
