### ISSUE TITLE
LastModifiedBy and CreatedBy annotation

### ISSUE THREAD

**Issue by ghahramani** [micronaut-projects/micronaut-data#506]
Hi,

I recently moved from Spring data to Micronaut and I was trying to do auto-populated for `createdBy` and `modifiedBy` fields but it seems Micronaut data only supports `@DateCreated` and `@DateUpdated`.

Would it be possible to add it or guide me on how to do it myself?

Thanks

**Comment by graemerocher** [comment]
We will be working on an events model for the next version

**Comment by meltzow** [comment]
hi, any news here?

**Comment by graemerocher** [comment]
This will be easier with the new events system https://github.com/micronaut-projects/micronaut-data/pull/900

**Comment by graemerocher** [comment]
Can be implemented quite easily now with entity events https://micronaut-projects.github.io/micronaut-data/snapshot/guide/#entityEvents

**Comment by eratio08** [comment]
@graemerocher Using the listeners does not allow to change the entity with an event hook (which would be required to insert such a user name). This is caused by `org.hibernate.action.internal.EntityInsertAction#execute` uses the `getState()` method which does return the state that was fixated before the hook. So changing the entity will not have any effect on whats is actually inserted.

**Comment by graemerocher** [comment]
@eratio08 For hibernate use the `setProperty` method of the event context to modify properties so the state is propagated correctly https://github.com/micronaut-projects/micronaut-data/blob/62c0e6319cae325ccf9d2d5d1181de3ff399147b/data-model/src/main/java/io/micronaut/data/event/EntityEventContext.java#L39
