### ISSUE TITLE
javax.transaction.Transactional does nothing when using Spring Jdbc Template for database operations

### ISSUE THREAD

**Issue by runarhk** [micronaut-projects/micronaut-data#651]
### Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Use javax.transaction.Transactional annotation to mark transactional boundaries
2. Use Spring jdbc template for persistence
3. Notice how database changes are not rolled back in case of an error. Auto-commits each change.

### Expected Behaviour

When an exception occurs, the database changes should be rolled back.

### Actual Behaviour

Database changes persist

### Environment Information

- **Operating System**: Linux Mint 19.3 Cinnamon
- **Micronaut Version:** 2.0.0
- **JDK Version:**  openjdk 11.0.7 2020-04-14

### Example Application

https://github.com/runarhk/mn_transactions_issues

Run PersonManagerTest to verify it is not working as intended

**Comment by runarhk** [comment]
@graemerocher pointed me to this annotation as a potential cause of the behaviour: 
https://github.com/micronaut-projects/micronaut-data/blob/master/data-tx/src/main/java/io/micronaut/transaction/jdbc/DataSourceTransactionManager.java#L91

**Comment by alejandropg** [comment]
We have the same problem.

I see that when you use `javax.transaction.Transactional` the Micronaut Annotation processor do their job, so the proxy `xxx$xxxDefinition` is generated, but then in runtime the `io.micronaut.transaction.interceptor.TransactionalInterceptor` is never called. In fact the interceptor is not in the chain.

I suppose that the interceptor is not in the chain because with the annotation `javax.transaction.Transactional` they try to find the Micronaut transaction manager but, as @runarhk sugest, it doesn't exist in favor of Spring's one.
