### ISSUE TITLE
Add JSON Column Support For Oracle

### ISSUE THREAD

**Issue by recursivecodes** [micronaut-projects/micronaut-data#712]
Add support for JSON columns in Oracle DB. See [docs](https://docs.oracle.com/en/database/oracle/oracle-database/19/adjsn/overview-of-storage-and-management-of-JSON-data.html#GUID-26AB85D2-3277-451B-BFAA-9DD45355FCC7).

**Comment by graemerocher** [comment]
@recursivecodes I added a test for this and it seems to be working since Oracle just stores JSON as regular fields. The additional constraint (https://docs.oracle.com/en/database/oracle/oracle-database/19/adjsn/creating-a-table-with-a-json-column.html#GUID-E6CC0DCF-3D72-41EF-ACA4-B3BF54EE3CA0) seems like something the user should apply in their Flyway/liquibase migrations

**Comment by graemerocher** [comment]
was there something you found that was not working with JSON columns?
