### ISSUE TITLE
Cascading save/persist not working with @OneToOne

### ISSUE THREAD

**Issue by matt-snider** [micronaut-projects/micronaut-data#815]
Persisting an entity that contains a `@OneToOne` relationship to a child entity should generate insert statements for both the parent and child entities.

## Task List

- [x] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Define the entities and repositories

```java
@Entity
public class Face {
    @GeneratedValue
    @Id
    private Long id;

   @OneToOne(cascade = CascadeType.PERSIST)
   private Nose nose;
  
   // Getters, setters
}

@Entity
public class Nose {
    @GeneratedValue
    @Id
    private Long id;
  
   // Getters, setters
}

public interface FaceRepository extends CrudRepository<Face, Long> { }

public interface NoseRepository extends CrudRepository<Face, Long> { }
```

2. Create and save entities

```java
Face face = new Face("Bob");
Nose nose = new Nose();
face.setNose(nose);

Face savedFace = faceRepository.save(face);
assertNotNull(savedFace.nose);
```

### Expected Behaviour

The child entity should be saved.

### Actual Behaviour

The child entity is not saved.

### Environment Information

- **Operating System**: NixOS 20.03
- **Micronaut Version:** 2.1.3
- **JDK Version:** 14

### Example Application

I added a test case displaying this issue:

https://github.com/matt-snider/micronaut-data/commit/b4dc0a9027d55f55a890dadcf696af718e9a9ae2

**Comment by thisarattr** [comment]
yes i'm experiencing the same it didnt even generate the insert for child object. Also tried both javax and micronaut annotations.

**Comment by issmo** [comment]
@matt-snider I am unable to reproduce the issue as you described it.

However, from the test case you produced, the issue is not in the save method which looks to work correctly.
The issue is that findById does not do a Join automatically to retrieve the entity. I think that this is by design as data-jdbc is not an ORM.

You can instruct micronaut data to do a join by decorating the findById method with @Join("nose"). This should work

**Comment by nhoughto** [comment]
I had this but stepping through the micronaut data code, I hit this condition
https://github.com/micronaut-projects/micronaut-data/blob/2.1.x/data-jdbc/src/main/java/io/micronaut/data/jdbc/operations/DefaultJdbcRepositoryOperations.java#L735

where it uses the `id` to check if it should insert it or not (which makes sense since no lazy loading/proxy objs), so cascading inserts only works in a world where ids are generated in some way, and not setup by the DAO/some other code itself it seems?

**Comment by nhoughto** [comment]
and the only way to have an `id` be generated (and not set ahead of time) seems to be to use Database IDENTITY or UUID from the app code. If we could override the `id` generation logic then we could probably make the current setup work (were using `long` for ids so no UUID compat).

uuid code
```
...
} else if (UUID.class.isAssignableFrom(beanProperty.getType())) {
                            value = UUID.randomUUID();
                            beanProperty.set(entity, value);
                        }
...
```

**Comment by tbeschastnyi** [comment]
Experiencing the same issue.
I've turned on TRACE logging and see that "cascaded" field is actually saved (Nose), however, it's id not filled to primary table (Face). Actually, "nose" insert goes after "face" insert what is not logically correct.

**Comment by matt-snider** [comment]
@tbeschastnyi Interesting. I hadn't thought of removing the NOT NULL constraint to see if the insert occurs, but in the wrong order, but that sounds like what would occur. I will try and test that out
